#!/usr/bin/env bash
# kernel/convert.sh — kernel conversion between distro packaging formats
#
# Converts a kernel from one distro's packaging format to another using lkf.
# Reads kernel metadata from the manifest and produces the target format.
#
# Supported conversions (all bidirectional):
#   deb  ↔  rpm  ↔  pkg.tar.zst  ↔  ebuild  ↔  apk  ↔  xbps
#
# Usage:
#   kernel/convert.sh --manifest system.manifest.toml \
#                     --target-distro arch \
#                     --target-arch amd64 \
#                     --output /tmp/kernel-output
#
# Requires: lkf (https://github.com/Interested-Deving-1896/lkf)

set -euo pipefail

source "$(dirname "${BASH_SOURCE[0]}")/../lib/manifest.sh"
source "$(dirname "${BASH_SOURCE[0]}")/../lib/log.sh"
source "$(dirname "${BASH_SOURCE[0]}")/../lib/arch.sh"

LKF_BIN="${LKF_BIN:-lkf}"
LKF_REPO="${LKF_REPO:-https://github.com/Interested-Deving-1896/lkf}"

# ── argument parsing ──────────────────────────────────────────────────────────
MANIFEST=""
TARGET_DISTRO=""
TARGET_ARCH=""
OUTPUT_DIR="${OUTPUT_DIR:-$(pwd)/kernel-output}"
JOBS="${JOBS:-$(nproc)}"
SOURCE_KERNEL=""   # override: path to existing kernel source tree

while [[ $# -gt 0 ]]; do
  case "$1" in
    --manifest)       MANIFEST="$2";       shift 2 ;;
    --target-distro)  TARGET_DISTRO="$2";  shift 2 ;;
    --target-arch)    TARGET_ARCH="$2";    shift 2 ;;
    --output)         OUTPUT_DIR="$2";     shift 2 ;;
    --jobs)           JOBS="$2";           shift 2 ;;
    --source-kernel)  SOURCE_KERNEL="$2";  shift 2 ;;
    *) die "Unknown option: $1" ;;
  esac
done

[[ -n "$MANIFEST" ]]      || die "--manifest is required"
[[ -n "$TARGET_DISTRO" ]] || die "--target-distro is required"

# ── distro → lkf output format ────────────────────────────────────────────────
distro_to_lkf_format() {
  case "$1" in
    debian|ubuntu|devuan) echo "deb" ;;
    arch)                 echo "pkg" ;;
    fedora)               echo "rpm" ;;
    alpine)               echo "apk" ;;
    void)                 echo "xbps" ;;
    opensuse)             echo "rpm" ;;
    gentoo)               echo "ebuild" ;;
    *) die "Unknown distro for kernel format: $1" ;;
  esac
}

# ── distro → lkf flavor ───────────────────────────────────────────────────────
distro_to_lkf_flavor() {
  case "$1" in
    debian|ubuntu|devuan|arch|fedora|alpine|void|opensuse) echo "generic" ;;
    gentoo) echo "gentoo" ;;
    *) echo "generic" ;;
  esac
}

# ── ensure lkf is available ───────────────────────────────────────────────────
ensure_lkf() {
  if command -v "$LKF_BIN" &>/dev/null; then
    log_verbose "lkf found: $(command -v "$LKF_BIN")"
    return 0
  fi
  log_info "lkf not found — cloning from ${LKF_REPO}..."
  git clone --depth=1 "$LKF_REPO" /opt/lkf
  ln -sf /opt/lkf/lkf.sh /usr/local/bin/lkf
  chmod +x /opt/lkf/lkf.sh
  LKF_BIN="lkf"
}

# ── generate a remix.toml for the conversion ─────────────────────────────────
generate_remix_toml() {
  local manifest="$1" target_distro="$2" target_arch="$3" remix_file="$4"

  local kver;    kver=$(manifest_read_field    "$manifest" "kernel.version")
  local flavor;  flavor=$(manifest_read_field  "$manifest" "kernel.flavor")
  local cmdline; cmdline=$(manifest_read_field "$manifest" "kernel.cmdline")
  local src_distro; src_distro=$(manifest_read_field "$manifest" "system.distro")

  [[ -z "$flavor" ]] && flavor="generic"
  [[ -z "$kver"   ]] && kver="latest"

  local lkf_format; lkf_format=$(distro_to_lkf_format "$target_distro")
  local lkf_flavor; lkf_flavor=$(distro_to_lkf_flavor "$target_distro")
  local cross_prefix; cross_prefix=$(arch_to_cross_prefix "$target_arch")
  local lkf_arch; lkf_arch=$(arch_to_rpm "$target_arch")  # lkf uses uname-style arch names

  cat > "$remix_file" << TOML
# Auto-generated by linux-pivot kernel/convert.sh
# Source: ${src_distro} kernel ${kver} (${flavor})
# Target: ${target_distro}/${target_arch}

[remix]
name        = "pivot-kernel-${target_distro}-${target_arch}"
version     = "${kver}"
flavor      = "${lkf_flavor}"
arch        = "${lkf_arch}"
description = "Kernel converted from ${src_distro} to ${target_distro}/${target_arch} by linux-pivot"

[build]
llvm         = false
lto          = "none"
threads      = ${JOBS}
config       = "defconfig"
target       = "generic"
output       = "${lkf_format}"
localversion = "-pivot"

[patches]
sets  = []
files = []

[cross]
prefix = "${cross_prefix}"

[output]
build_dir    = "${OUTPUT_DIR}/build"
download_dir = "${OUTPUT_DIR}/downloads"
clean_after  = false
remove_after = false
TOML

  # If we have a source kernel tree, point lkf at it
  if [[ -n "$SOURCE_KERNEL" && -d "$SOURCE_KERNEL" ]]; then
    echo "" >> "$remix_file"
    echo "[lkf_hook]" >> "$remix_file"
    echo "source_tree = \"${SOURCE_KERNEL}\"" >> "$remix_file"
  fi

  log_verbose "remix.toml written: ${remix_file}"
}

# ── main ──────────────────────────────────────────────────────────────────────
main() {
  [[ -f "$MANIFEST" ]] || die "Manifest not found: ${MANIFEST}"

  local src_distro; src_distro=$(manifest_read_field "$MANIFEST" "system.distro")
  local src_arch;   src_arch=$(manifest_read_field   "$MANIFEST" "system.arch")
  local kver;       kver=$(manifest_read_field       "$MANIFEST" "kernel.version")
  local target_arch="${TARGET_ARCH:-${src_arch}}"

  log_step "Kernel conversion: ${src_distro} → ${TARGET_DISTRO}/${target_arch}"
  log_info "  kernel version: ${kver}"
  log_info "  output format:  $(distro_to_lkf_format "$TARGET_DISTRO")"
  log_info "  output dir:     ${OUTPUT_DIR}"

  ensure_lkf
  mkdir -p "$OUTPUT_DIR"

  local remix_file="${OUTPUT_DIR}/pivot-kernel.toml"
  generate_remix_toml "$MANIFEST" "$TARGET_DISTRO" "$target_arch" "$remix_file"

  log_info "Running: lkf remix ${remix_file}"
  "$LKF_BIN" remix "$remix_file"

  log_info "Kernel conversion complete — output in ${OUTPUT_DIR}"
}

[[ "${BASH_SOURCE[0]}" == "$0" ]] && main
