#!/usr/bin/env bash
# installers/common.sh — distro-agnostic install helpers
#
# Each distro installer sources this file, then implements:
#   bootstrap_distro()   → fetch + unpack stage3 into TARGET
#   install_packages()   → translate + install manifest packages
#   configure_init()     → enable services from manifest
#   configure_bootloader() → install + configure bootloader
#
# Common functions here handle: user creation, fstab, network,
# locale, hostname, preserve paths, kernel install.

source "$(dirname "${BASH_SOURCE[0]}")/../lib/manifest.sh"
source "$(dirname "${BASH_SOURCE[0]}")/../lib/log.sh"
source "$(dirname "${BASH_SOURCE[0]}")/../lib/arch.sh"
source "$(dirname "${BASH_SOURCE[0]}")/../lib/pkgmap.sh"
source "$(dirname "${BASH_SOURCE[0]}")/../lib/chroot.sh"

STAGE3_REPO="${STAGE3_REPO:-Interested-Deving-1896/linux-distro-stage3}"

# ── fetch stage3 from linux-distro-stage3 releases ───────────────────────────
fetch_stage3() {
  local distro="$1" release="$2" arch="$3" dest="$4"
  local api_url="https://api.github.com/repos/${STAGE3_REPO}/releases/latest"
  local pattern="${distro}_stage3_${release}_${arch}_"

  log_info "Fetching stage3 for ${distro}/${release}/${arch}..."
  local url
  url=$(curl -fsSL "$api_url" \
    | grep browser_download_url \
    | grep "${pattern}" \
    | grep -v '\.sha256' \
    | tr -d '"' \
    | sed 's/.*browser_download_url: //' \
    | head -1)

  [[ -n "$url" ]] || die "No stage3 found for ${distro}/${release}/${arch} in ${STAGE3_REPO}"
  log_info "Downloading: ${url}"
  curl -fL "$url" -o "$dest"
}

# ── apply preserved paths from source to target ───────────────────────────────
apply_preserved_paths() {
  local manifest="$1" source_root="$2" target_root="$3"
  local paths_raw; paths_raw=$(manifest_read_field "$manifest" "preserve.paths")

  # Default preserve paths if not set
  local paths=("/home" "/root" "/etc/ssh/ssh_host_*" "/etc/ssl/certs")
  [[ -n "$paths_raw" ]] && IFS=',' read -ra paths <<< "$paths_raw"

  for path_pattern in "${paths[@]}"; do
    path_pattern="${path_pattern// /}"
    for src in ${source_root}${path_pattern}; do
      [[ -e "$src" ]] || continue
      local rel="${src#${source_root}}"
      local dst_dir="${target_root}$(dirname "$rel")"
      mkdir -p "$dst_dir"
      cp -a "$src" "${target_root}${rel}" 2>/dev/null || true
      log_verbose "preserved: ${rel}"
    done
  done
}

# ── apply users from manifest ─────────────────────────────────────────────────
apply_users() {
  local manifest="$1" target_root="$2" source_root="${3:-/}"
  local users_raw; users_raw=$(manifest_read_field "$manifest" "users.raw")
  [[ -z "$users_raw" ]] && return 0

  IFS='|' read -ra user_entries <<< "$users_raw"
  for entry in "${user_entries[@]}"; do
    [[ -z "$entry" ]] && continue
    IFS=':' read -r name uid gid home shell <<< "$entry"
    in_chroot "$target_root" useradd \
      --uid "$uid" --gid "$gid" \
      --home-dir "$home" --shell "$shell" \
      --no-create-home "$name" 2>/dev/null || true
    log_verbose "user: ${name} (${uid}:${gid})"
  done

  # Copy shadow entries
  if [[ -f "${source_root}/etc/shadow" ]]; then
    while IFS=: read -r name hash rest; do
      grep -q "^${name}:" "${target_root}/etc/shadow" 2>/dev/null && \
        sed -i "s|^${name}:.*|${name}:${hash}:${rest}|" "${target_root}/etc/shadow" || true
    done < "${source_root}/etc/shadow"
  fi
}

# ── apply fstab from manifest ─────────────────────────────────────────────────
apply_fstab() {
  local manifest="$1" target_root="$2"
  local fstab_raw; fstab_raw=$(manifest_read_field "$manifest" "fstab.raw")
  [[ -z "$fstab_raw" ]] && return 0

  # Write fstab (pipe-separated entries → newline-separated)
  echo "# Generated by linux-pivot" > "${target_root}/etc/fstab"
  echo "${fstab_raw//|/$'\n'}" >> "${target_root}/etc/fstab"
  log_verbose "fstab: applied"
}

# ── apply hostname ────────────────────────────────────────────────────────────
apply_hostname() {
  local manifest="$1" target_root="$2"
  local hostname; hostname=$(manifest_read_field "$manifest" "system.hostname")
  [[ -z "$hostname" ]] && return 0
  echo "$hostname" > "${target_root}/etc/hostname"
  log_verbose "hostname: ${hostname}"
}

# ── apply locale + timezone ───────────────────────────────────────────────────
apply_locale() {
  local manifest="$1" target_root="$2"
  local locale; locale=$(manifest_read_field "$manifest" "system.locale")
  local tz; tz=$(manifest_read_field "$manifest" "system.timezone")

  [[ -n "$locale" ]] && {
    mkdir -p "${target_root}/etc"
    echo "LANG=${locale}" > "${target_root}/etc/locale.conf"
  }
  [[ -n "$tz" ]] && {
    ln -sf "/usr/share/zoneinfo/${tz}" "${target_root}/etc/localtime" 2>/dev/null || true
    echo "$tz" > "${target_root}/etc/timezone" 2>/dev/null || true
  }
  log_verbose "locale: ${locale} tz: ${tz}"
}

# ── run all common install steps ──────────────────────────────────────────────
install_common() {
  local manifest="$1" target_root="$2" source_root="${3:-/}"

  apply_hostname "$manifest" "$target_root"
  apply_locale   "$manifest" "$target_root"
  apply_fstab    "$manifest" "$target_root"
  apply_users    "$manifest" "$target_root" "$source_root"
  apply_preserved_paths "$manifest" "$source_root" "$target_root"
}
